name: Build LaTeX document
on: 
  # push:
  #   branches: 
  #     - main
  # # Allows the workflow to be started manually
  # workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR_paper: seminar_paper
      DIR_presentation: presentation
      FILE: main
      PDF_paper: seminar_paper.pdf
      PDF_presentation: seminar_paper.pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install texlive
        run: sudo apt update && sudo apt install texlive texlive-publishers texlive-science 
      - name: Compile Seminar Paper
        run: cd ${{env.DIR_paper}}; pdflatex -interaction=nonstopmode ${{env.FILE}}.tex; bibtex ${{env.FILE}}; pdflatex -interaction=nonstopmode ${{env.FILE}}.tex; pdflatex -interaction=nonstopmode ${{env.FILE}}.tex
        continue-on-error: true
      - name: Move Paper
        run: echo $PWD; mkdir -p github_artifacts && mv ${{env.DIR_paper}}/${{env.FILE}}.pdf ./github_artifacts/${{env.PDF_paper}}
      - name: Compile Presentation
        run: cd ${{env.DIR_presentation}}; pdflatex -interaction=nonstopmode ${{env.FILE}}.tex; pdflatex -interaction=nonstopmode ${{env.FILE}}.tex; 
        continue-on-error: true
      - name: Move Presentation
        run: echo $PWD; mkdir -p github_artifacts && mv ${{env.DIR_presentation}}/${{env.FILE}}.pdf ./github_artifacts/${{env.PDF_presentation}}
      - name: Upload seminar_presentation.pdf Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.PDF_paper}}
          path: ./github_artifacts
      - name: Upload presentation.pdf Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.PDF_presentation}}
          path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: gh_pages
          force_orphan: true
