name: Build LaTeX document
on: 
  # push:
    # branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: seminar_paper
      FILE: main
      PDF: paper.pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install texlive
        run: sudo apt update && sudo apt install texlive texlive-publishers texlive-science 
      - name: Compile Seminar Paper
        run: cd ${{env.DIR}}; pdflatex -interaction=nonstopmode ${{env.FILE}}.tex; bibtex ${{env.FILE}}; pdflatex -interaction=nonstopmode ${{env.FILE}}.tex; pdflatex -interaction=nonstopmode ${{env.FILE}}.tex
        continue-on-error: true
      # - name: Install TUM template
      #   run: sudo bash ./ci-install.sh
      # - name: Compile Presentation
      #   run: cd ${{env.DIR}}; pdflatex -interaction=nonstopmode
      - name: Move Artifacts
        run: echo $PWD; mkdir -p github_artifacts && mv ${{env.DIR}}/${{env.FILE}}.pdf ./github_artifacts/${{env.PDF}}
      - name: Upload pdf Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.PDF}}
          path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: gh_pages
          force_orphan: true
