name: Build LaTeX document
on: 
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILE: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: apt update
        run: sudo apt update
      - name: install TUM template
        run: wget 'https://gitlab.lrz.de/latex4ei/tum-templates/-/jobs/artifacts/v2.0.0/raw/build/tum-latex-templates-2.0.0.deb' && sudo apt install ./*.deb
      - name: Install texlive
        run: sudo apt update && sudo apt install texlive texlive-publishers texlive-science 
      - name: Compile LaTeX document
        run: pdflatex ${{env.FILE}}; bibtex ${{env.FILE}}; pdflatex ${{env.FILE}}; pdflatex ${{env.FILE}};
      - name: move artifact
        run: mkdir -p github_artifacts && mv ${{env.FILE}}.pdf ./github_artifacts/
      - name: upload pdf artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.FILE}}.pdf
          path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: gh_pages
          force_orphan: true
